using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Anti
{
    internal class DG
    {
		public static HashSet<string> debuggertitles = new HashSet<string>();
		public static HashSet<string> debuggertitles2 = new HashSet<string>();
		public static void DebuggersList()
		{
			if (debuggertitles.Count > 0 && debuggertitles2.Count > 0)
			{
				return;
			}
			debuggertitles.Add("procmon64");
			debuggertitles.Add("codecracker");
			debuggertitles.Add("x96dbg");
			debuggertitles.Add("pizza");
			debuggertitles.Add("pepper");
			debuggertitles.Add("reverse");
			debuggertitles.Add("reversal");
			debuggertitles.Add("de4dot");
			debuggertitles.Add("pc-ret");
			debuggertitles.Add("crack");
			debuggertitles.Add("ILSpy");
			debuggertitles.Add("x32dbg");
			debuggertitles.Add("sharpod");
			debuggertitles.Add("x64dbg");
			debuggertitles.Add("x32_dbg");
			debuggertitles.Add("x64_dbg");
			debuggertitles.Add("debug");
			debuggertitles.Add("dbg");
			debuggertitles.Add("strongod");
			debuggertitles.Add("PhantOm");
			debuggertitles.Add("titanHide");
			debuggertitles.Add("scyllaHide");
			debuggertitles.Add("ilspy");
			debuggertitles.Add("graywolf");
			debuggertitles.Add("simpleassemblyexplorer");
			debuggertitles.Add("MegaDumper");
			debuggertitles.Add("megadumper");
			debuggertitles.Add("X64NetDumper");
			debuggertitles.Add("x64netdumper");
			debuggertitles.Add("HxD");
			debuggertitles.Add("hxd");
			debuggertitles.Add("PETools");
			debuggertitles.Add("petools");
			debuggertitles.Add("Protection_ID");
			debuggertitles.Add("protection_id");
			debuggertitles.Add("die");
			debuggertitles.Add("process hacker 2");
			debuggertitles.Add("process");
			debuggertitles.Add("hacker");
			debuggertitles.Add("ollydbg");
			debuggertitles.Add("ida -");
			debuggertitles.Add("charles");
			debuggertitles.Add("dnspy");
			debuggertitles.Add("simpleassembly");
			debuggertitles.Add("peek");
			debuggertitles.Add("httpanalyzer");
			debuggertitles.Add("httpanalyzerstdv7");
			debuggertitles.Add("httpdebug");
			debuggertitles.Add("fiddler");
			debuggertitles.Add("wireshark");
			debuggertitles.Add("proxifier");
			debuggertitles.Add("mitmproxy");
			debuggertitles.Add("process hacker");
			debuggertitles.Add("process monitor");
			debuggertitles.Add("system explorer");
			debuggertitles.Add("systemexplorer");
			debuggertitles.Add("systemexplorerservice");
			debuggertitles.Add("WPE PRO");
			debuggertitles.Add("ghidra");
			debuggertitles.Add("folderchangesview");
			debuggertitles.Add("folder");
			debuggertitles.Add("dump");
			debuggertitles.Add("proxy");
			debuggertitles.Add("de4dotmodded");
			debuggertitles.Add("StringDecryptor");
			debuggertitles.Add("Centos");
			debuggertitles.Add("SAE");
			debuggertitles.Add("monitor");
			debuggertitles.Add("brute");
			debuggertitles.Add("zed");
			debuggertitles.Add("sniffer");
			debuggertitles.Add("http");
			debuggertitles.Add("debugger");
			debuggertitles.Add("james");
			debuggertitles.Add("exeinfope");
			debuggertitles.Add("dbx");
			debuggertitles.Add("mdbg");
			debuggertitles.Add("gdb");
			debuggertitles.Add("windbg");
			debuggertitles.Add("dnspy");
			debuggertitles.Add("ida");
			debuggertitles.Add("dbgclr");
			debuggertitles.Add("kdb");
			debuggertitles.Add("kgdb");
			debuggertitles.Add("mdb");
			debuggertitles.Add("processhacker");
			debuggertitles.Add("scylla_x86");
			debuggertitles.Add("scylla_x64");
			debuggertitles.Add("scylla");
			debuggertitles.Add("idau64");
			debuggertitles.Add("idau");
			debuggertitles.Add("idaq");
			debuggertitles.Add("idaq64");
			debuggertitles.Add("idaw");
			debuggertitles.Add("idaw64");
			debuggertitles.Add("idag");
			debuggertitles.Add("idag64");
			debuggertitles.Add("ida64");
			debuggertitles.Add("ImportREC");
			debuggertitles.Add("IMMUNITYDEBUGGER");
			debuggertitles.Add("CodeBrowser");
			debuggertitles.Add("reshacker");
			debuggertitles.Add("cheat engine");
			debuggertitles.Add("ollydbg");
			debuggertitles.Add("ida");
			debuggertitles.Add("ida64");
			debuggertitles.Add("idag");
			debuggertitles.Add("idag64");
			debuggertitles.Add("idaw");
			debuggertitles.Add("idaw64");
			debuggertitles.Add("idaq");
			debuggertitles.Add("idaq64");
			debuggertitles.Add("idau");
			debuggertitles.Add("idau64");
			debuggertitles.Add("scylla");
			debuggertitles.Add("scylla_x64");
			debuggertitles.Add("scylla_x86");
			debuggertitles.Add("protection_id");
			debuggertitles.Add("x64dbg");
			debuggertitles.Add("x32dbg");
			debuggertitles.Add("windbg");
			debuggertitles.Add("reshacker");
			debuggertitles.Add("importrec");
			debuggertitles.Add("immunitydebugger");
			debuggertitles.Add("megadumper");
			debuggertitles.Add("dnspy");
			debuggertitles.Add("charles");
			debuggertitles.Add("http toolkit");
			debuggertitles.Add("http debugger");
			debuggertitles.Add("fiddler");
			debuggertitles.Add("ilspy");
			debuggertitles.Add("0harmony");
			debuggertitles.Add("sharpod");
			debuggertitles.Add("xd");
			debuggertitles.Add("extremedumper");
			debuggertitles.Add("dojandqwklndoqwd");
			debuggertitles.Add("dojandqwklndoqwd-x86");
			debuggertitles.Add("ksdumper");
			debuggertitles.Add("ksdumper v1.1 - by equifox");
			debuggertitles.Add("x32_dbg");
			debuggertitles.Add("x64_dbg");
			debuggertitles.Add("strongod");
			debuggertitles.Add("phantom");
			debuggertitles.Add("titanhide");
			debuggertitles.Add("scyllahide");
			debuggertitles.Add("graywolf");
			debuggertitles.Add("simpleassemblyexplorer");
			debuggertitles.Add("x64netdumper");
			debuggertitles.Add("process hacker 2");
			debuggertitles.Add("ida -");
			debuggertitles.Add("httpanalyzer");
			debuggertitles.Add("httpdebug");
			debuggertitles.Add("wireshark");
			debuggertitles.Add("proxifier");
			debuggertitles.Add("mitmproxy");
			debuggertitles.Add("process hacker");
			debuggertitles.Add("process monitor");
			debuggertitles.Add("system explorer");
			debuggertitles.Add("systemexplorer");
			debuggertitles.Add("systemexplorerservice");
			debuggertitles.Add("wpe pro");
			debuggertitles.Add("ghidra");
			debuggertitles.Add("harmony");
			debuggertitles.Add("dbx");
			debuggertitles.Add("mdbg");
			debuggertitles.Add("gdb");
			debuggertitles.Add("dbgclr");
			debuggertitles.Add("kdb");
			debuggertitles.Add("httpdebugger");
			debuggertitles.Add("kgdb");
			debuggertitles.Add("mdb");
			debuggertitles.Add("dumper");
			debuggertitles.Add("folderchangesview");
			debuggertitles2.Add("ilspy");
			debuggertitles2.Add("0harmony");
			debuggertitles2.Add("x32dbg");
			debuggertitles2.Add("sharpod");
			debuggertitles2.Add("xd");
			debuggertitles2.Add("extremedumper");
			debuggertitles2.Add("dojandqwklndoqwd");
			debuggertitles2.Add("dojandqwklndoqwd-x86");
			debuggertitles2.Add("ida");
			debuggertitles2.Add("renamed by lockt (x86)");
			debuggertitles2.Add("lockt");
			debuggertitles2.Add("by lockt");
			debuggertitles2.Add("renamed by");
			debuggertitles2.Add("astro renamer");
			debuggertitles2.Add("-astro");
			debuggertitles2.Add("ksdumper");
			debuggertitles2.Add("ksdumper v1.1 - by equifox");
			debuggertitles2.Add("x64dbg");
			debuggertitles2.Add("x32_dbg");
			debuggertitles2.Add("x64_dbg");
			debuggertitles2.Add("strongod");
			debuggertitles2.Add("phantom");
			debuggertitles2.Add("titanhide");
			debuggertitles2.Add("scyllahide");
			debuggertitles2.Add("graywolf");
			debuggertitles2.Add("simpleassemblyexplorer");
			debuggertitles2.Add("megadumper");
			debuggertitles2.Add("x64netdumper");
			debuggertitles2.Add("process hacker 2");
			debuggertitles2.Add("ollydbg");
			debuggertitles2.Add("ida -");
			debuggertitles2.Add("charles");
			debuggertitles2.Add("dnspy");
			debuggertitles2.Add("httpanalyzer");
			debuggertitles2.Add("httpdebug");
			debuggertitles2.Add("fiddler");
			debuggertitles2.Add("wireshark");
			debuggertitles2.Add("proxifier");
			debuggertitles2.Add("mitmproxy");
			debuggertitles2.Add("process hacker");
			debuggertitles2.Add("process monitor");
			debuggertitles2.Add("system explorer");
			debuggertitles2.Add("systemexplorer");
			debuggertitles2.Add("systemexplorerservice");
			debuggertitles2.Add("wpe pro");
			debuggertitles2.Add("ghidra");
			debuggertitles2.Add("harmony");
			debuggertitles2.Add("http debugger");
			debuggertitles2.Add("dbx");
			debuggertitles2.Add("mdbg");
			debuggertitles2.Add("gdb");
			debuggertitles2.Add("windbg");
			debuggertitles2.Add("dbgclr");
			debuggertitles2.Add("kdb");
			debuggertitles2.Add("httpdebugger");
			debuggertitles2.Add("kgdb");
			debuggertitles2.Add("mdb");
			debuggertitles2.Add("folderchangesview");
			debuggertitles2.Add("disassembly");
			debuggertitles2.Add("scylla");
			debuggertitles2.Add("debug");
			debuggertitles2.Add("[cpu");
			debuggertitles2.Add("immunity");
			debuggertitles2.Add("import reconstructor");
			debuggertitles2.Add("dumper");
			debuggertitles2.Add("megadumper 1.0 by codecracker / snd");
			debuggertitles2.Add("http toolkit");
			debuggertitles2.Add("procmon64");
			debuggertitles2.Add("codecracker");
			debuggertitles2.Add("x96dbg");
			debuggertitles2.Add("pizza");
			debuggertitles2.Add("pepper");
			debuggertitles2.Add("reverse");
			debuggertitles2.Add("reversal");
			debuggertitles2.Add("de4dot");
			debuggertitles2.Add("pc-ret");
			debuggertitles2.Add("crack");
			debuggertitles2.Add("ILSpy");
			debuggertitles2.Add("x32dbg");
			debuggertitles2.Add("sharpod");
			debuggertitles2.Add("x64dbg");
			debuggertitles2.Add("x32_dbg");
			debuggertitles2.Add("x64_dbg");
			debuggertitles2.Add("debug");
			debuggertitles2.Add("dbg");
			debuggertitles2.Add("strongod");
			debuggertitles2.Add("PhantOm");
			debuggertitles2.Add("titanHide");
			debuggertitles2.Add("scyllaHide");
			debuggertitles2.Add("ilspy");
			debuggertitles2.Add("graywolf");
			debuggertitles2.Add("simpleassemblyexplorer");
			debuggertitles2.Add("MegaDumper");
			debuggertitles2.Add("megadumper");
			debuggertitles2.Add("X64NetDumper");
			debuggertitles2.Add("x64netdumper");
			debuggertitles2.Add("HxD");
			debuggertitles2.Add("hxd");
			debuggertitles2.Add("PETools");
			debuggertitles2.Add("petools");
			debuggertitles2.Add("Protection_ID");
			debuggertitles2.Add("protection_id");
			debuggertitles2.Add("die");
			debuggertitles2.Add("process hacker 2");
			debuggertitles2.Add("process");
			debuggertitles2.Add("hacker");
			debuggertitles2.Add("ollydbg");
			debuggertitles2.Add("ida -");
			debuggertitles2.Add("charles");
			debuggertitles2.Add("dnspy");
			debuggertitles2.Add("simpleassembly");
			debuggertitles2.Add("peek");
			debuggertitles2.Add("httpanalyzer");
			debuggertitles2.Add("httpdebug");
			debuggertitles2.Add("fiddler");
			debuggertitles2.Add("wireshark");
			debuggertitles2.Add("proxifier");
			debuggertitles2.Add("mitmproxy");
			debuggertitles2.Add("process hacker");
			debuggertitles2.Add("process monitor");
			debuggertitles2.Add("system explorer");
			debuggertitles2.Add("systemexplorer");
			debuggertitles2.Add("systemexplorerservice");
			debuggertitles2.Add("WPE PRO");
			debuggertitles2.Add("ghidra");
			debuggertitles2.Add("folderchangesview");
			debuggertitles2.Add("folder");
			debuggertitles2.Add("dump");
			debuggertitles2.Add("proxy");
			debuggertitles2.Add("de4dotmodded");
			debuggertitles2.Add("StringDecryptor");
			debuggertitles2.Add("Centos");
			debuggertitles2.Add("SAE");
			debuggertitles2.Add("monitor");
			debuggertitles2.Add("brute");
			debuggertitles2.Add("zed");
			debuggertitles2.Add("sniffer");
			debuggertitles2.Add("http");
			debuggertitles2.Add("debugger");
			debuggertitles2.Add("james");
			debuggertitles2.Add("exeinfope");
			debuggertitles2.Add("dbx");
			debuggertitles2.Add("mdbg");
			debuggertitles2.Add("gdb");
			debuggertitles2.Add("windbg");
			debuggertitles2.Add("dnspy");
			debuggertitles2.Add("ida");
			debuggertitles2.Add("dbgclr");
			debuggertitles2.Add("kdb");
			debuggertitles2.Add("kgdb");
			debuggertitles2.Add("mdb");
			debuggertitles2.Add("processhacker");
			debuggertitles2.Add("scylla_x86");
			debuggertitles2.Add("scylla_x64");
			debuggertitles2.Add("scylla");
			debuggertitles2.Add("idau64");
			debuggertitles2.Add("idau");
			debuggertitles2.Add("idaq");
			debuggertitles2.Add("idaq64");
			debuggertitles2.Add("idaw");
			debuggertitles2.Add("idaw64");
			debuggertitles2.Add("idag");
			debuggertitles2.Add("idag64");
			debuggertitles2.Add("ida64");
			debuggertitles2.Add("ImportREC");
			debuggertitles2.Add("IMMUNITYDEBUGGER");
			debuggertitles2.Add("CodeBrowser");
			debuggertitles2.Add("reshacker");
			debuggertitles2.Add("cheat engine");
			debuggertitles2.Add("ida64");
			debuggertitles2.Add("idag");
			debuggertitles2.Add("idag64");
			debuggertitles2.Add("idaw");
			debuggertitles2.Add("idaw64");
			debuggertitles2.Add("idaq");
			debuggertitles2.Add("idaq64");
			debuggertitles2.Add("idau");
			debuggertitles2.Add("idau64");
			debuggertitles2.Add("scylla_x64");
			debuggertitles2.Add("scylla_x86");
			debuggertitles2.Add("protection_id");
			debuggertitles2.Add("reshacker");
			debuggertitles2.Add("importrec");
			debuggertitles2.Add("immunitydebugger");
			debuggertitles.Add("renamed by lockt (x86)");
			debuggertitles.Add("lockt");
			debuggertitles.Add("by lockt");
			debuggertitles.Add("renamed by");
			debuggertitles.Add("astro renamer");
			debuggertitles.Add("-astro");
			debuggertitles.Add("disassembly");
			debuggertitles.Add("debug");
			debuggertitles.Add("[cpu");
			debuggertitles.Add("immunity");
			debuggertitles.Add("import reconstructor");
			debuggertitles.Add("megadumper 1.0 by codecracker / snd");
		}
	}
}
